#! /bin/sh
#
# This forms the basis for the nf-config utility, which tells you
# various things about the netCDF Fortran installation.


prefix=C:/Program Files/NC4F
exec_prefix=C:/Program Files/NC4F
libdir=C:/Program Files/NC4F/lib
includedir=C:/Program Files/NC4F/include
fmoddir=C:/Program Files/NC4F/include
#
cc="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe"
fc="C:/Program Files (x86)/Intel/oneAPI/compiler/2022.2.0/windows/bin/intel64/ifort.exe"
cflags="-IC:/Program Files/NC4F/include /DWIN32 /D_WINDOWS /W3 -O2 "
fflags="-I${includedir} -I${fmoddir}"
#
has_dap="no"
has_nc2="yes"
has_nc4="yes"
has_f90="TRUE"
has_f03="yes"
flibs="-L${libdir} -lnetcdff -lnetcdf -lnetcdf "
version=" 4.6.2-development"

 usage()
 {
         echo
         echo "This $version has been built with the following features: "
         echo
         echo "  --cc        -> $cc"
         echo "  --cflags    -> $cflags"
         echo
         echo "  --fc        -> $fc"
         echo "  --fflags    -> $fflags"
         echo "  --flibs     -> $flibs"
         echo "  --has-f90   -> $has_f90"
         echo "  --has-f03   -> $has_f03"
         echo
         echo "  --has-nc2   -> $has_nc2"
         echo "  --has-nc4   -> $has_nc4"
 	echo
         echo "  --prefix    -> $prefix"
         echo "  --includedir-> $includedir"
         echo "  --version   -> $version"
         echo
 }

 if test $# -eq 0; then
     usage 1
 fi

 while test $# -gt 0; do
     case "$1" in
      #this deals with options in the style
      #--option=value and extracts the value part
      #[not currently used]
     -*=*) value=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
     *) value= ;;
     esac

     case "$1" in

     --help)
 	usage 0
 	;;

     --all)
 	all
 	;;

     --cc)
 	echo $cc
 	;;

     --fc)
 	echo $fc
 	;;

     --cflags)
 	echo $cflags
 	;;

     --fflags)
 	echo $fflags
 	;;

     --has-dap)
        	echo $has_dap
        	;;

     --has-nc2)
        	echo $has_nc2
        	;;

     --has-nc4)
        	echo $has_nc4
        	;;

     --has-f90)
        	echo $has_f90
        	;;

     --has-f03)
        	echo $has_f03
        	;;

     --flibs)
        	echo $flibs
        	;;

     --prefix)
        	echo "${CMAKE_INSTALL_PREFIX}"
        	;;

     --includedir)
        	echo "${includedir}"
        	;;

     --version)
 	echo $version
 	;;

     *)
         echo "unknown option: $1"
 	usage
 	exit 1
 	;;
     esac
     shift
 done

 exit 0
