# CMake generated Testfile for 
# Source directory: C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4
# Build directory: C:/work/netcdf/netcdf-fortran-main-4.6.1/MyBuild/nf_test4
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ftst_groups "ftst_groups")
set_tests_properties(ftst_groups PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_vars "ftst_vars")
set_tests_properties(ftst_vars PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_vars2 "ftst_vars2")
set_tests_properties(ftst_vars2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_vars3 "ftst_vars3")
set_tests_properties(ftst_vars3 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_vars4 "ftst_vars4")
set_tests_properties(ftst_vars4 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_vars5 "ftst_vars5")
set_tests_properties(ftst_vars5 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_vars6 "ftst_vars6")
set_tests_properties(ftst_vars6 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_types "ftst_types")
set_tests_properties(ftst_types PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_types2 "ftst_types2")
set_tests_properties(ftst_types2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_types3 "ftst_types3")
set_tests_properties(ftst_types3 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_path "ftst_path")
set_tests_properties(ftst_path PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_rengrps "ftst_rengrps")
set_tests_properties(ftst_rengrps PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(f03tst_open_mem "f03tst_open_mem")
set_tests_properties(f03tst_open_mem PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_var_compact "ftst_var_compact")
set_tests_properties(ftst_var_compact PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
add_test(ftst_v2 "ftst_v2")
set_tests_properties(ftst_v2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;73;ADD_TEST;C:/work/netcdf/netcdf-fortran-main-4.6.1/netcdf-fortran-main/nf_test4/CMakeLists.txt;0;")
