FROM nvcr.io/nvidia/nvhpc:20.11-devel-cuda_multi-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y libnetcdf-dev build-essential autoconf automake libtool pkg-config tzdata
# copy the compilers
RUN cd /opt/nvidia/hpc_sdk/Linux_x86_64/20.11/REDIST/compilers && tar -czvhf /root/nvidia-20.11.tar.gz * && cd -
WORKDIR /usr/src/sfincs
COPY . /usr/src/sfincs
# ccall ->  Generate code for all compute capabilities supported by this platform and by the selected or default CUDA Toolkit.
RUN autoreconf -vif && FCFLAGS="-acc -Minfo=accel -fast -O3 -gpu=ccall -DSIZEOF_PTRDIFF_T=8" FC=nvfortran ./configure --disable-shared --disable-openmp  && make && make install

FROM nvidia/cuda:11.2.2-runtime-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y libnetcdf-dev tzdata
# copy nvidia SDK (REDIST folder contains symlinks)
COPY --from=0 /root/nvidia-20.11.tar.gz .
# copy software
COPY --from=0 /usr/local /usr/local
RUN mkdir -p /opt/nvidia/compilers
RUN tar -xzf nvidia-20.11.tar.gz -C /opt/nvidia/compilers
# add the REDIST libs to the environment
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/nvidia/compilers/lib
VOLUME /data
WORKDIR /data
CMD ["sfincs"]
